### PR TITLE
Add serialization and deserialization of job errors

### PR DESCRIPTION
**Pull request by perrin4869**
As discussed in issue #40, for your consideration :)

### CODE REVIEW

**Comment by LewisJEllis** [comment]
Thanks! At a quick glance it generally looks good, and it seems you've covered your bases on documentation and testing. I'll do a more thorough review tonight.

**Comment by AurelienRibon** [comment]
This is a much required feature ! Stack traces are completely lost over the network, making debug process a total pain. Please merge this PR if it works fine, the world will thank you :D

**Comment by skeggse** [comment]
Stack traces are now preserved in the job itself in the `job.options.stacktraces` Array. I think a more cohesive approach to error serialization that includes both storing this kind of data _and_ publishing is warranted. I like that your solution is pluggable, and would be happy to review a revised PR that also stores the serialized errors in Redis.

**Comment by perrin4869** [comment]
Hm... been a long time since I worked on this and have lost interest since... Don't have any plans to update it. You can close it if you want

**Comment by samuelgoldenbaum** [comment]
need to get this up and running - really is needed

**Pull request closed without merging**
