### PR TITLE
Upgrade redis to 3.0.2

### PR DESCRIPTION
**Pull request by b-jam**
Fixes https://github.com/bee-queue/bee-queue/issues/253

### CODE REVIEW

**Comment by b-jam** [comment]
Unsure why CI is failing, but it works for me in an app using TLS, and `yarn test` runs fine locally

**Comment by skeggse** [comment]
This project uses `npm` - please use `npm` to upgrade `redis` as that'll avoid the `yarn.lock` and will update the `package-lock.json`. CI is failing because the two package files aren't in sync.

**Comment by b-jam** [comment]
Ah. It looks better now, but incompatible with node 4 so that checks failing still

**Comment by b-jam** [comment]
Hey @skeggse is it important to keep node 4 happy, or can I perhaps remove it from travis, and add a lts like `lts/erbium` ?

**Comment by skeggse** [comment]
We'll have to wait to deprecate Node 4 support for bee-queue v2, which is currently on hold pending an owner.

**Comment by b-jam** [comment]
Sure, can I merge this into `2.0dev` then instead ?

**Comment by b-jam** [comment]
Nevermind - I see thats using ioredis anyway

**Comment by skeggse** [comment]
One of 2.0's main features is moving to `ioredis`, so I'm not sure that's the right move. Did Redis 3 drop Node 4 support?

If this is something you want internally, you should be able to just pass a Redis 3 connection in to the Queue constructor.

**Comment by b-jam** [comment]
https://github.com/NodeRedis/node-redis/blob/master/.github/workflows/tests.yml
looks like it judging from their CI which only runs v6+

ah that sounds like a better solution than forking. Will check it out

**Comment by b-jam** [comment]
As a note, I tried using a 3.0 connection but it just didn't work. Didn't do a deep dive why, just that it didn't work after I changed it to a 3.0 connection to the same redis, TLS or not.

I will patiently wait for bq 2.0 :)

**Pull request closed without merging**
