### PR TITLE
fix: queues stop working when there are more than 8k jobs with the same timestamp

### PR DESCRIPTION
**Pull request by compwright**
Resubmitting https://github.com/bee-queue/bee-queue/pull/192 from @Tob0t and @mattbornski to rebase and re-run CI checks:

> Since there is no progress on #123 I created another PR.
> 
> FYI: The commit from @mattbornski was taken.
> 
> Since our queues stopped working if there are more than 8k jobs with the same timestamp, we needed a fix asap. I know that the PR was not merged since there could be a further improvements. However as @mattbornski mentioned, better this fix with blocking redis for short time than processing no jobs at all.
> 
> We are already using this code on our production system since we needed a fix asap.
> 
> Disclaimer: I'm not a lua programmer, so feel free to adapt the PR ;)

### CODE REVIEW

**Review by bradvogel — APPROVED** [review]
Approving.

It looks like this was [approved here](https://github.com/bee-queue/bee-queue/pull/123#pullrequestreview-136017280) but with [this concern](https://github.com/bee-queue/bee-queue/pull/123#pullrequestreview-349581747). However, I agree with the comment in the PR description that it's better to block Redis than to not process at all.

**Comment by compwright** [comment]
@tmeasday care to add a review before we move on this?

**Comment by tmeasday** [comment]
Seems reasonable but it would be good to have a test I guess (I'm no expert on how these tests work anymore, or ever really).

**Comment by bradvogel** [comment]
@tmeasday You're absolutely right. I complete overlooked the fact that there wasn't a test 🤦‍♂️. I think this is OK to skip one for now since it's unlikely the original author is interested in adding one now.

**Pull request merged**
