### PR TITLE
fix(types): add types for saveAll()

### PR DESCRIPTION
**Pull request by chris-askbrian**
#318 This should solve the missing types for this function

### CODE REVIEW

**Review by bradvogel — APPROVED** [review]

**Comment by bradvogel** [comment]
@chris-askbrian mind fixing the CI failure? Amend your commit message to something like `chore(types): add types for saveAll()`

**Comment by rodrake1** [comment]
When is this going to be merged?

**Comment by wu-json** [comment]
Can we get this merged soon?

**Comment by compwright** [comment]
Resubmitted as https://github.com/bee-queue/bee-queue/pull/553

**Pull request closed without merging**
